language: haskell

sudo: false

before_install:
  - export PATH=/opt/ghc/7.8.4/bin:$PATH
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.2.0/stack-0.1.2.0-x86_64-linux.gz | gunzip > ~/.local/bin/stack
  - chmod a+x ~/.local/bin/stack
  # selenium
  - cd misc/selenium
  - mkdir log
  - "export DISPLAY=:1"
  - make xvfb
  - make init
  - make start
  - cd ../..

install:
  - travis_wait stack setup

script:
  - travis_wait 45 stack test

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.8.4
    - xvfb

cache:
  directories:
    - $HOME/.stack
