language: haskell
ghc: 7.8
before_install:
    - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
    - travis_retry sudo apt-get update
    - travis_retry sudo apt-get install --force-yes happy-1.19.3 alex-3.1.3 cabal-install-1.22
    - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.3/bin:/opt/cabal/1.22/bin:$PATH
    - export PATH=~/.cabal/bin:$PATH
    - travis_retry sudo apt-get install xvfb
    - cd misc/selenium
    - mkdir log
    - "export DISPLAY=:1"
    - make xvfb
    - make init
    - make start
    - cd ../..
install:
    - cabal install hlint
    - ./misc/thentos-install.sh
script:
    - make hlint
    - cd thentos-tests && cabal test && cd ..
    - cd thentos-adhocracy && cabal test && cd ..
