language: haskell
ghc: 7.8
before_install:
    - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
    - travis_retry sudo apt-get update
    - travis_retry sudo apt-get install --force-yes happy-1.19.3 alex-3.1.3 cabal-install-1.22
    - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.3/bin:/opt/cabal/1.22/bin:$PATH
    - export PATH=~/.cabal/bin:$PATH
    - travis_retry sudo apt-get install xvfb
    - cd misc/selenium
    - mkdir log
    - "export DISPLAY=:1"
    - make xvfb
    - make init
    - make start
    - cd ../..
install:
    - ./misc/get-cabal-config.sh stack.yaml cabal.config
    - cp cabal.config thentos-core/cabal.config
    - cp cabal.config thentos-tests/cabal.config
    - cp cabal.config thentos-adhocracy/cabal.config
    - ./misc/thentos-install.sh
    - git clone --depth 1 https://github.com/liqd/travis-cache
    - export PATH=$PWD/travis-cache:$PATH
    - mkdir -p ./hlint/.cabal-sandbox/share/x86_64-linux-ghc-7.8.4
    - cp -r travis-cache/data ./hlint/.cabal-sandbox/share/x86_64-linux-ghc-7.8.4/hlint-1.9.21/
script:
    - make hlint
    - cd thentos-core && cabal configure --ghc-options="-Werror" && cabal build && cd ..
    - cd thentos-tests && cabal configure --ghc-options="-Werror" && cabal build && cabal test && cd ..
    - cd thentos-adhocracy && cabal configure --ghc-options="-Werror" && cabal build && cabal test && cd ..
