# We use --force-reinstalls to allow caching. If this causes problems, go to
# https://travis-ci.org/liqd/thentos/caches to invalidate the cache.

language: c

sudo: false

cache:
    directories:
        - $HOME/build/liqd/thentos/.cabal-sandbox
        - $HOME/.cabal
        - $HOME/.nvm
        - $HOME/.th-psc-cache

addons:
    apt:
        sources:
            - hvr-ghc
        packages:
            - ghc-7.10.2
            - happy-1.19.3
            - alex-3.1.4
            - cabal-install-1.22
            - xvfb
            - espeak
            - sox
            - hlint

before_install:
    - grep '\(MemTotal\|SwapTotal\)' /proc/meminfo
    - git show | head -1  # (for matching against commit hash given on the travis log web page)
    - export PATH=/opt/ghc/7.10.2/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.3/bin:/opt/cabal/1.22/bin:$PATH
    - export PATH=~/.cabal/bin:$PATH
    - cd misc/selenium
    - "export DISPLAY=:1"
    - make init xvfb start
    - cd ../..

script:
    - rm -rf $HOME/build/liqd/thentos/.cabal-sandbox
    - ./.travis/script.sh
