sudo: false
language: haskell
ghc: 7.8
addons:
  apt:
    packages:
    - xvfb
before_install:
    - cd misc/selenium
    - mkdir log
    - "export DISPLAY=:1"
    - make xvfb
    - make init
    - make start
    - cd ../..
install:
    - ./misc/get-cabal-config.sh stack.yaml cabal.config
    - cp cabal.config thentos-core/cabal.config
    - cp cabal.config thentos-tests/cabal.config
    - cp cabal.config thentos-adhocracy/cabal.config
    - ./misc/thentos-install.sh
    - git clone --depth 1 https://github.com/liqd/travis-cache
    - export PATH=$PWD/travis-cache:$PATH
    - mkdir -p ./hlint/.cabal-sandbox/share/x86_64-linux-ghc-7.8.4
    - cp -r travis-cache/data ./hlint/.cabal-sandbox/share/x86_64-linux-ghc-7.8.4/hlint-1.9.21/
script:
    - make hlint
    - (cd thentos-core && cabal configure --ghc-options="-Werror" && cabal build)
    - (cd thentos-tests && cabal configure --ghc-options="-Werror" && cabal build && cabal test)
    - (cd thentos-adhocracy && cabal configure --ghc-options="-Werror" && cabal build && cabal test)
