language: haskell
before_install:
    - grep '\(MemTotal\|SwapTotal\)' /proc/meminfo
    - git show | head -1  # (for matching against commit hash given on the travis log web page)
    - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
    - travis_retry sudo apt-get update
    - travis_retry sudo apt-get install --force-yes ghc-7.10.2 happy-1.19.3 alex-3.1.3 cabal-install-1.22 hlint
    - export PATH=/opt/ghc/7.10.2/bin:/opt/alex/3.1.3/bin:/opt/happy/1.19.3/bin:/opt/cabal/1.22/bin:$PATH
    - export PATH=~/.cabal/bin:$PATH
    - travis_retry sudo apt-get install xvfb
    - cd misc/selenium
    - mkdir log
    - "export DISPLAY=:1"
    - make xvfb
    - make init
    - make start
    - cd ../..
install:
    - ./misc/thentos-install.sh
    - export PATH=$PWD/travis-cache:$PATH
script:
    - make hlint
    - (cd thentos-core && cabal configure --ghc-options="-Werror" && cabal build)
    - (cd thentos-tests && cabal configure --ghc-options="-Werror" && cabal build && cabal test)
    - (cd thentos-adhocracy && cabal configure --ghc-options="-Werror" && cabal build && cabal test)
