flags: {}
packages:
- 'thentos-core'
- 'thentos-tests'
- 'thentos-adhocracy'
- location: 'submodules/servant/servant'
  extra-dep: true
- location: 'submodules/servant/servant-server'
  extra-dep: true
- location: 'submodules/servant/servant-client'
  extra-dep: true
- location: 'submodules/servant/servant-docs'
  extra-dep: true
- location: 'submodules/servant/servant-jquery'
  extra-dep: true
- location:
    git: https://github.com/jkarni/configifier.git
    commit: eb63dcf356483b6464b7a0c719edb71aaf1931d0
  extra-dep: true
extra-deps:
- digestive-functors-blaze-0.6.0.6
- digestive-functors-snap-0.6.1.3
- functor-infix-0.0.3
- lio-0.11.5.0
- scrypt-0.5.0
- servant-pandoc-0.4.1
- snaplet-acid-state-0.2.7
- regex-easy-0.1.0.0

resolver: nightly-2015-07-12
