flags: {}
packages:
- 'thentos-core'
- 'thentos-tests'
- 'thentos-adhocracy'
- 'services/helloworld'
- location: 'submodules/servant/servant'
  extra-dep: true
- location: 'submodules/servant/servant-server'
  extra-dep: true
- location: 'submodules/servant/servant-client'
  extra-dep: true
- location: 'submodules/servant/servant-docs'
  extra-dep: true
- location: 'submodules/servant/servant-jquery'
  extra-dep: true
extra-deps:
- acid-state-0.12.4
- configifier-0.0.5
- cryptonite-0.5
- digestive-functors-0.8.0.0
- digestive-functors-blaze-0.6.0.6
- digestive-functors-snap-0.6.1.3
- email-validate-2.1.3
- functor-infix-0.0.3
- hspec-2.1.8
- hspec-core-2.1.8
- hspec-discover-2.1.8
- hspec-expectations-0.7.0
- lio-0.11.5.0
- regex-easy-0.1.0.0
- regex-pcre-0.94.4
- sandi-0.3.5
- scrypt-0.5.0
- snap-blaze-0.2.1.3
- snap-loader-static-0.9.0.2
- snaplet-acid-state-0.2.7
- uri-bytestring-0.1.6

resolver: lts-2.18
