flags: {}
ghc-options:
  thentos-core: -Werror
  thentos-tests: -Werror
  thentos-adhocracy: -Werror
packages:
- 'thentos-core'
- 'thentos-tests'
- 'thentos-adhocracy'
- 'services/helloworld'
- location: 'submodules/servant/servant'
  extra-dep: true
- location: 'submodules/servant/servant-server'
  extra-dep: true
- location: 'submodules/servant/servant-client'
  extra-dep: true
- location: 'submodules/servant/servant-docs'
  extra-dep: true
- location: 'submodules/pronk'
  extra-dep: true
extra-deps:
- attoparsec-0.13.0.1
- configifier-0.0.5
- digestive-functors-0.8.0.0
- digestive-functors-blaze-0.6.0.6
- digestive-functors-snap-0.6.1.3
- email-validate-2.1.3
- functor-infix-0.0.3
- lio-0.11.5.0
- regex-easy-0.1.0.0
- regex-pcre-0.94.4
- sandi-0.3.5
- scrypt-0.5.0
- snap-blaze-0.2.1.3
- snap-loader-static-0.9.0.2
- meldable-heap-2.0.3

resolver: lts-3.5
